### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by Libardo1** [andrew-couch/Tidy-Tuesday#1]
Andrew, thanks for share.
I am reproducing your code; everything is fine except for this Chunk:

```{r}
#Get test metrics
main_wf %>% last_fit(main_split) %>% collect_metrics()
int_wf %>% last_fit(main_split) %>% collect_metrics()
```
I get this error message:
Error in split_to_rset(split) : objeto 'main_split' no encontrado

I would appreciate any clue to solve it.

TIA,

**Comment by andrew-couch** [comment]
Oops, I accidentally specified the wrong tidy split object. Instead of main_split, it should be replaced with tidy_split. I have made the correct changes.
