### ISSUE TITLE
Error: The app required missing column "year"

### ISSUE THREAD

**Issue by tanviranjum21** [andrew-couch/Tidy-Tuesday#3]
Hi Andrew,

I have found an error while running the code on my machine it is showing that "The following required columns are missing: 'year'." I have added year as input in my code then it works fine. I have attached the screenshot regarding the error. 

<img width="1432" alt="Screenshot 2020-10-24 at 9 05 53 PM" src="https://user-images.githubusercontent.com/34216156/97085075-defe7900-163c-11eb-87b9-f4fb537a4e33.png">

**Comment by andrew-couch** [comment]
@Tanvir-21 I'm not sure why that error would occur for the penguin app. Are you sure you have the correct model loaded? Here's the code for checking the model's predictors. 

`model$pre$mold$predictors`

The command should only output the training data used.
![Screenshot 2020-10-24 104108](https://user-images.githubusercontent.com/52845042/97085829-71732e00-15e5-11eb-843a-6d2410ee6b87.png)
